spring.application.name=districtcoolingsystem
spring.datasource.url=jdbc:mysql://localhost:3306/district_cooling
spring.datasource.username=root
spring.datasource.password=Root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080